### ISSUE TITLE
Report doesn't have name

### ISSUE THREAD

**Issue by razielsd** [allure-framework/allure-phpunit#26]
When first test used dataProvider, then xml-report  doesn't exists tag name. Example:

```php
<?php

class Debug_BugTest extends PHPUnit_Framework_TestCase
{
    public function providerCaseOne()
    {
        return [
            [1], [2], [3]
        ];
    }


    /**
     * some text
     *
     * @dataProvider providerCaseOne
     */
    public function testCaseOne()
    {
        //Some implementation here...
    }

}
```

report
```xml
<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" start="1411748186977" stop="1411748186980" version="1.4.0">
  <name>Debug_BugTest::testCaseOne</name><!-- name exists -->
  <test-cases>
    <test-case start="1411748186978" stop="1411748186979" status="passed">
      <name>Debug_BugTest382testCaseOne with data set #0</name>
    </test-case>
    <test-case start="1411748186979" stop="1411748186979" status="passed">
      <name>Debug_BugTest382testCaseOne with data set #1</name>
    </test-case>
    <test-case start="1411748186979" stop="1411748186980" status="passed">
      <name>Debug_BugTest382testCaseOne with data set #2</name>
    </test-case>
  </test-cases>
</alr:test-suite>
```
Add second test:
```php
<?php

class Debug_BugTest extends PHPUnit_Framework_TestCase
{
    public function providerCaseOne()
    {
        return [
            [1], [2], [3]
        ];
    }


    /**
     * some text
     *
     * @dataProvider providerCaseOne
     */
    public function testCaseOne()
    {
        //Some implementation here...
    }


    /**
     * add this test
     *
     */
    public function testCaseTwo()
    {
        //Some implementation here...
    }
}
```
xml-report
```xml
<?xml version="1.0" encoding="UTF-8"?>
<alr:test-suite xmlns:alr="urn:model.allure.qatools.yandex.ru" stop="1411748355125" version="1.4.0">
<!-- name NOT exists -->
  <test-cases>
    <test-case start="1411748355125" stop="1411748355125" status="passed">
      <name>Debug_BugTest382testCaseTwo</name>
    </test-case>
  </test-cases>
</alr:test-suite>
```
and make html-report:
```
allure generate allure-results/ -o report -v 1.4.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by
log4j:ERROR [java.net.URLClassLoader@3004baef] whereas object of type
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@18fb53f6].
log4j:ERROR Could not instantiate appender named "console".
Exception in thread "pool-1-thread-5" java.lang.NumberFormatException: For input string: "NaN"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:441)
        at java.lang.Long.valueOf(Long.java:540)
        at com.sun.xml.internal.bind.DatatypeConverterImpl._parseLong(DatatypeConverterImpl.java:109)
        at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$18.parse(RuntimeBuiltinLeafInfoImpl.java:726)
        at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$18.parse(RuntimeBuiltinLeafInfoImpl.java:724)
        at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:230)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:194)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:486)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:465)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:135)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(AbstractXMLDocumentParser.java:182)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:355)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2770)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:203)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:181)
        at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:235)
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:242)
        at ru.yandex.qatools.allure.data.providers.XUnitDataProvider.provide(XUnitDataProvider.java:26)
        at ru.yandex.qatools.allure.data.AllureReportGenerator$1.async(AllureReportGenerator.java:58)
        at ru.yandex.qatools.allure.data.AllureReportGenerator$1.async(AllureReportGenerator.java:55)
        at ru.yandex.qatools.allure.data.utils.Async$1.run(Async.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Validation error at xsl:call-template on line 20
  FORG0001: Cannot convert string "NaN" to an integer
  in built-in template rule
Exception in thread "pool-1-thread-6" ru.yandex.qatools.allure.data.ReportGenerationException: ValidationException: Cannot convert string "NaN" to an integer
        at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:55)
        at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:44)
        at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:35)
        at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformations(XslTransformationUtils.java:29)
        at ru.yandex.qatools.allure.data.providers.EnvironmentProvider.provide(EnvironmentProvider.java:37)
        at ru.yandex.qatools.allure.data.AllureReportGenerator$1.async(AllureReportGenerator.java:58)
        at ru.yandex.qatools.allure.data.AllureReportGenerator$1.async(AllureReportGenerator.java:55)
        at ru.yandex.qatools.allure.data.utils.Async$1.run(Async.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
Caused by: ValidationException: Cannot convert string "NaN" to an integer
        at net.sf.saxon.type.ValidationFailure.makeException(ValidationFailure.java:233)
        at net.sf.saxon.expr.UntypedAtomicConverter$1.map(UntypedAtomicConverter.java:156)
        at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:46)
        at net.sf.saxon.expr.ItemMappingIterator.next(ItemMappingIterator.java:39)
        at net.sf.saxon.expr.CardinalityChecker.evaluateItem(CardinalityChecker.java:262)
        at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:296)
        at net.sf.saxon.expr.ExpressionTool.lazyEvaluate(ExpressionTool.java:437)
        at net.sf.saxon.functions.ExtensionFunctionCall.iterate(ExtensionFunctionCall.java:221)
        at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:352)
        at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:296)
        at net.sf.saxon.instruct.GeneralVariable.getSelectValue(GeneralVariable.java:374)
        at net.sf.saxon.instruct.Instruction.assembleParams(Instruction.java:147)
        at net.sf.saxon.instruct.CallTemplate.process(CallTemplate.java:253)
        at net.sf.saxon.instruct.CallTemplate.processLeavingTail(CallTemplate.java:281)
        at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:556)
        at net.sf.saxon.instruct.Instruction.process(Instruction.java:93)
        at net.sf.saxon.instruct.ElementCreator.processLeavingTail(ElementCreator.java:296)
        at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:203)
        at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:345)
        at net.sf.saxon.instruct.ApplyTemplates.defaultAction(ApplyTemplates.java:378)
        at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:333)
        at net.sf.saxon.Controller.transformDocument(Controller.java:1807)
        at net.sf.saxon.Controller.transform(Controller.java:1621)
        at ru.yandex.qatools.allure.data.utils.XslTransformationUtils.applyTransformation(XslTransformationUtils.java:52)
        ... 10 more
Successfully generated report to [/home/razielsd/projects/tests/avito.ru/avito-tests-ru/tests/build/report].
```

**Comment by tyz910** [comment]
possibly fixed in #32 - same problem with DataProvider

**Comment by vania-pooh** [comment]
@razielsd could you confirm that this is fixed?

**Comment by razielsd** [comment]
try until week confirm

**Comment by razielsd** [comment]
bug fixed, thanks a lot
